# Het aanwezig zijn van de .travis.yml is voldoende om aan Travis te laten weten
# dat het bij push naar github onderstaande commandos moet uitvoeren.

# Er wordt superuser machtiging vereist
sudo: required
# docker moet geïnstalleerd zijn om de commandos te kunnen uitvoeren.
services:
  - docker

# image opbouwen
before_install:
  - docker build -t kurtvanhal/docker-react -f Dockerfile.dev .

script:
  # travis vereist een status 0 exit code van het process. Onderstaand commando
  # doet dit standaard niet, maar wacht op input voor verdere tests.
  # -- --coverage zal het process wel beeïndigen.
  - docker run -e CI=true kurtvanhal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-506608664154"
  bucket_path: "dokcer-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
